;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagRedirects=(OldTagName="Weapon.Attachments.Scope",NewTagName="Weapon.Attachments.Sight")
+GameplayTagRedirects=(OldTagName="Weapon.Aim.Sight",NewTagName="Weapon.Aim.DefaultAim")
+GameplayTagList=(Tag="Weapon.Aim",DevComment="")
+GameplayTagList=(Tag="Weapon.Aim.DefaultAim",DevComment="")
+GameplayTagList=(Tag="Weapon.Aim.Scope",DevComment="")
+GameplayTagList=(Tag="Weapon.Ammo.Explosive",DevComment="")
+GameplayTagList=(Tag="Weapon.Ammo.Heavy",DevComment="")
+GameplayTagList=(Tag="Weapon.Ammo.Light",DevComment="")
+GameplayTagList=(Tag="Weapon.Ammo.Medium",DevComment="")
+GameplayTagList=(Tag="Weapon.Attachments.Barrel",DevComment="")
+GameplayTagList=(Tag="Weapon.Attachments.Barrel.Attached",DevComment="")
+GameplayTagList=(Tag="Weapon.Attachments.Grip",DevComment="")
+GameplayTagList=(Tag="Weapon.Attachments.Grip.Attached",DevComment="")
+GameplayTagList=(Tag="Weapon.Attachments.Sight",DevComment="")
+GameplayTagList=(Tag="Weapon.Attachments.Sight.Attached",DevComment="")
+GameplayTagList=(Tag="Weapon.BulletMode.Projectile",DevComment="")
+GameplayTagList=(Tag="Weapon.BulletMode.Trace",DevComment="")
+GameplayTagList=(Tag="Weapon.FireMode",DevComment="")
+GameplayTagList=(Tag="Weapon.FireMode.Auto",DevComment="")
+GameplayTagList=(Tag="Weapon.FireMode.Burst",DevComment="")
+GameplayTagList=(Tag="Weapon.FireMode.CanSwitch",DevComment="")
+GameplayTagList=(Tag="Weapon.FireMode.Single",DevComment="")
+GameplayTagList=(Tag="Weapon.States.CanFire",DevComment="")

